version: "3.4"
services:
 client:
    image: node:alpine
    container_name: client
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
        - ./client:/srv/app
        - /srv/app/node_modules
    tty: true
    command: clientEntrypoint.sh

 server:
   image: node:alpine
   container_name: server
   entrypoint: /bin/sh
   ports:
     - 7000:7000
   working_dir: /srv/app
   environment:
      NODE_ENV: development
   volumes:
       - ./server:/srv/app
       - /srv/app/node_modules
   tty: true
   command: serverEntrypoint.sh




volumes:
  node_modules: